[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend && cd backend && npx prisma generate"

[deploy]
startCommand = "cd backend && node_modules/.bin/prisma db push && node src/index.js"
