[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend && cd backend && npx prisma generate"

[deploy]
startCommand = "cd backend && npx prisma db push && cd .. && node backend/src/index.js"
